import { BASEURL } from "./config";
// el menu esta relacionado con un multidioma
export const listaMenu = [
    {
        id: 590,
        title: "inicio",
        icon: "material-symbols:in-home-mode-outline",
        color: "primary",
        url: `${BASEURL}/dashboard`,
        private:false
      },
      {
        id: 440,
        title: "informes",
        icon: "mdi:graph-bell-curve",
        color: "#a0aec0",
        open:false,
        sub:true,
        submenu:[
          {
            id:2,
            url: `${BASEURL}/informes`,
            title:'Informes_Generales',
            icon: "mdi:report-bell-curve-cumulative",
            color: "#a0aec0",
          },
          {
            id:3,
            url: `${BASEURL}/informesproductos`,
            title:'Informes_Productos',
            icon: "ph:archive-box-duotone",
            color: "#a0aec0",
          },
        ],
        
      },
      {
        id:580,
        title: "agendas",
        icon:"material-symbols:calendar-month-outline-sharp",
        open:false,
        sub:true,
        submenu:[
          {
            id:5,
            title:'agenda',
            icon:'mdi:calendar-search-outline',
            color: "#a0aec0",
            url:`${BASEURL}/agenda`,
          },
        ]
      },
      {
        id: 530,
        title: "ventas",
        icon: "ic:twotone-sell",
        color: "#a0aec0",
        url: "url",
        open:false,
        sub:true,
        submenu: [
          {
            id: 7,
            title: "nueva_venta",
            url: `${BASEURL}/ventas`,
            icon: "ic:twotone-point-of-sale",
            color: "#a0aec0",
          },    
          {
            id: 8,
            title: "notas_pedidos",
            url: `${BASEURL}/notas`,
            icon: "ic:round-receipt-long",
            color: "#a0aec0",
          },
          {
            id: 6,
            title: "lista_facturas",
            url: `${BASEURL}/facturas`,
            icon: "ic:twotone-receipt-long",
            color: "#a0aec0",
          },
          {
            id: 10,
            title: "comisiones",
            url: `${BASEURL}/comisiones`,
            icon: `ic:twotone-paid`,
            color: "#a0aec0",
          },
          {
            id: 12,
            title: "formas_de_pago",
            url: `${BASEURL}/formaspago`,
            icon: "ph:wallet-duotone",
            color: "#a0aec0",
          },
          {
            id: 14,
            title: "entregas",
            url: `${BASEURL}/entregas`,
            icon: "icon-park-twotone:delivery",
            color: "#a0aec0",
          },
          {
            id: 62,
            title: "pedidos",
            url: `${BASEURL}/pedidos`,
            icon: "carbon:delivery",
            color: "#a0aec0",
          },
          {
            id: 16,
            title: "reportes",
            url: `${BASEURL}/reportes`,
            icon: "ic:twotone-summarize",
            color: "#a0aec0",
          },
        ],
      },
      {
        id: 540,
        title: "productos",
        icon: "ic:twotone-inventory",
        color: "#a0aec0",
        open:false,
        sub:true,
        submenu: [
          {
            id: 18,
            title: "agregar",
            icon: "ic:twotone-add-business",
            color: "#a0aec0",
            url: `${BASEURL}/productos/new`,
          },
          {
            id: 17,
            title: "lista_productos",
            icon: "ic:twotone-content-paste",
            color: "#a0aec0",
            url: `${BASEURL}/productos`,
          },
          {
            id: 19,
            title: "categorias",
            icon: "ic:twotone-category",
            color: "#a0aec0",
            url: `${BASEURL}/categorias`,
          },
          {
            id: 21,
            title: "proveedores",
            url: `${BASEURL}/proveedores`,
            icon: "ic:twotone-local-shipping",
            color: "#a0aec0",
          },
          {
            id: 23,
            title: "marcas",
            url: `${BASEURL}/marcas`,
            icon: "tabler:brand-among-us",
            color: "#a0aec0",
          },
          {
            id: 25,
            title: "apartados",
            icon: "ic:twotone-save",
            color: "#a0aec0",
            url: `${BASEURL}/apartados`,
          },
          
          {
            id:27,
            title:"depositos",
            url:`${BASEURL}/depositos`,
            icon:"ic:twotone-local-convenience-store",
            color:"#a0aec0",
          },
          {
            id:30,
            title:"transferencias",
            url:`${BASEURL}/transferencias`,
            icon:"ic:twotone-sync-alt",
            color:"#a0aec0",
          },
          {
            id: 31,
            title: "inventario",
            icon: "ic:twotone-handyman",
            color: "#a0aec0",
            url: `${BASEURL}/inventario`,
          },
        ],
      },
      

      {
        id: 55,
        title: "arqueos",
        icon: "ic:twotone-savings",
        color: "#a0aec0",
        open:false,
        sub:true,
        submenu: [
          {
            id: 33,
            title: "cajas",
            url: `${BASEURL}/cajas`,
            icon: `ic:sharp-point-of-sale`,
            color: "#a0aec0",
          },
          {
            id: 36,
            title: "mov__caja",
            url: `${BASEURL}/movimientos`,
            icon: `ph:sneaker-move-light`,
            color: "#a0aec0",
          },
          {
            id: 37,
            title: "registros__mov",
            url: `${BASEURL}/registromovimientos`,
            icon: `carbon:container-registry`,
            color: "#a0aec0",
         },
        ],
      },
      {
        id: 31,
        title: "compras",
        icon: "ph:basket-duotone",
        color: "#a0aec0",
        url: `${BASEURL}/compras`,
      },
      {
        id: 38,
        title: "cuentas",
        icon: "ic:twotone-payments",
        color: "#a0aec0",
        url: `${BASEURL}/cuentas`,
      },
      {
        id: 560,
        title: "mantenimiento",
        icon: "ic:twotone-developer-board",
        color: "#a0aec0",
        open:false,
        sub:true,
        submenu: [
          {
            id: 40,
            title: "clientes",
            url: `${BASEURL}/clientes`,
            icon: "ic:twotone-people-alt",
            color: "#a0aec0",
          },
          {
            id: 42,
            title: "empleados",
            url: `${BASEURL}/empleados`,
            icon: "material-symbols:badge-outline-rounded",
            color: "#a0aec0",
          },
    
          {
            id: 44,
            title: "monedas",
            url: `${BASEURL}/monedas`,
            icon: "mdi:money-100",
            color: "#a0aec0",
          },
          {
            id: 46,
            title: "unidad_medida",
            icon: "ic:twotone-square-foot",
            color: "#a0aec0",
            url: `${BASEURL}/medidas`,
          },
          {
            id: 48,
            title: "impuestos",
            icon: "tabler:receipt-tax",
            color: "#a0aec0",
            url: `${BASEURL}/impuestos`,
          },
          {
            id: 49,
            title: "usuarios",
            icon: "ic:twotone-account-box",
            color: "#a0aec0",
            url: `${BASEURL}/users`,
          },
          {
            id: 51,
            title: "actividad",
            icon: "carbon:user-activity",
            color: "#a0aec0",
            url: `${BASEURL}/actividad`,
          },
        ],
      },
    
      {
        id: 57,
        title: "ajustes",
        icon: "icon-park-twotone:setting-two",
        color: "#a0aec0",
        private:false,
        open: false,
        sub:true,
        submenu: [
          {
            id: 52,
            title: "datos_empresa",
            icon: "ic:twotone-admin-panel-settings",
            color: "#a0aec0",
            url: `${BASEURL}/settings`,
          },
          {
            id: 54,
            title: "registro_facturas",
            icon: "ic:twotone-receipt-long",
            color: "#a0aec0",
            url: `${BASEURL}/registrofacturas`,
          },
          {
            id: 57,
            title: "tema_y_colores",
            icon: "ic:twotone-palette",
            color: "#a0aec0",
            url: `${BASEURL}/tema`,
          },
          {
            id: 56,
            title: "backup",
            icon: "flat-color-icons:data-backup",
            color: "#a0aec0",
            url: `${BASEURL}/backup`,
          },
          {
            id: 58,
            title: "info_y_ayuda",
            icon: "ic:twotone-help-center",
            color: "#a0aec0",
            url: `${BASEURL}/info`,
            private:false
          },

          {
            id: 59,
            title: "sitio_web",
            icon: "mdi:web-check",
            color: "#a0aec0",
            url: `${BASEURL}/web`,
            private:true
          },

        ],
        
      },
        
]