import { BASEURL } from "./config";
export const listaMenu = [
    {
        id: 59,
        title: "Inicio",
        icon: "apps",
        color: "#a0aec0",
        url: `${BASEURL}/dashboard`,
      },
      {
        id: 44,
        title: "Informes",
        icon: "trending_up",
        color: "#a0aec0",
        url: `${BASEURL}/informes`,
      },
      {
        id:58,
        title: "Agendas",
        open:false,
        icon:"calendar_month",
        submenu:[
          {
            id:49,
            title:'Turnos',
            icon:'login',
            color: "#a0aec0",
            url:`${BASEURL}/turnos`,
          },
          {
            id:51,
            title:'Agenda',
            icon:'date_range',
            color: "#a0aec0",
            url:`${BASEURL}/agenda`,
          },
        ]
      },
      {
        id: 53,
        title: "Ventas",
        icon: "sell",
        color: "#a0aec0",
        url: "url",
        open: false,
        submenu: [
          {
            id: 1,
            title: "Nueva venta",
            url: `${BASEURL}/ventas`,
            icon: "point_of_sale",
            color: "#a0aec0",
          },    
          {
            id: 6,
            title: "Notas",
            url: `${BASEURL}/notas`,
            icon: "receipt",
            color: "#a0aec0",
          },
          {
            id: 4,
            title: "Lista Facturas",
            url: `${BASEURL}/facturas`,
            icon: "assignment",
            color: "#a0aec0",
          },
          {
            id: 16,
            title: "Entregas",
            url: `${BASEURL}/entregas`,
            icon: "delivery_dining",
            color: "#a0aec0",
          },
        ],
      },
      {
        id: 54,
        title: "Productos",
        icon: "inventory_2",
        color: "#a0aec0",
        open: false,
        submenu: [
          {
            id: 91,
            title: "Agregar",
            icon: "diamond",
            color: "#a0aec0",
            url: `${BASEURL}/productos/new`,
          },
          {
            id: 8,
            title: "Lista de productos",
            icon: "content_paste",
            color: "#a0aec0",
            url: `${BASEURL}/productos`,
          },
  
          {
            id: 10,
            title: "Categorías",
            icon: "category",
            color: "#a0aec0",
            url: `${BASEURL}/categorias`,
          },
          {
            id: 14,
            title: "Proveedores",
            url: `${BASEURL}/proveedores`,
            icon: "local_shipping",
            color: "#a0aec0",
          },
          {
            id: 12,
            title: "Marcas",
            url: `${BASEURL}/marcas`,
            icon: "branding_watermark",
            color: "#a0aec0",
          },
          {
            id: 18,
            title: "Apartados",
            icon: "save",
            color: "#a0aec0",
            url: `${BASEURL}/apartados`,
          },
          
          {
            id:39,
            title:"Depositos",
            url:`${BASEURL}/depositos`,
            icon:"local_convenience_store",
            color:"#a0aec0",
          },
          {
            id:60,
            title:"Transferencias",
            url:`${BASEURL}/transferencias`,
            icon:"sync_alt",
            color:"#a0aec0",
          },
          {
            id: 43,
            title: "Inventario",
            icon: "handyman",
            color: "#a0aec0",
            url: `${BASEURL}/inventario`,
          },
        ],
      },
      
      {
        id: 20,
        title: "Compras",
        icon: "shopping_basket",
        color: "#a0aec0",
        url: `${BASEURL}/compras`,
      },
      {
        id: 55,
        title: "Arqueos",
        icon: "savings",
        color: "#a0aec0",
        open: false,
        submenu: [
          {
            id: 22,
            title: "Cajas",
            url: `${BASEURL}/cajas`,
            icon: `point_of_sale`,
            color: "#a0aec0",
          },
          {
            id: 24,
            title: "Mov. de cajas",
            url: `${BASEURL}/movimientos`,
            icon: `leaderboard`,
            color: "#a0aec0",
          },
          {
            id: 26,
            title: "Registro de mov.",
            url: `${BASEURL}/registromovimientos`,
            icon: `app_registration`,
            color: "#a0aec0",
         },
        ],
      },{
        id: 47,
        title: "Cuentas",
        icon: "payments",
        color: "#a0aec0",
        url: `${BASEURL}/cuentas`,
      },
      {
        id: 56,
        title: "Mantenimiento",
        icon: "engineering",
        color: "#a0aec0",
        open: false,

        submenu: [
          {
            id: 28,
            title: "Clientes",
            url: `${BASEURL}/clientes`,
            icon: "people",
            color: "#a0aec0",
          },
          {
            id: 41,
            title: "Empleados",
            url: `${BASEURL}/empleados`,
            icon: "badge",
            color: "#a0aec0",
          },
    
          {
            id: 30,
            title: "Monedas",
            url: `${BASEURL}/monedas`,
            icon: "monetization_on",
            color: "#a0aec0",
          },
          {
            id: 32,
            title: "Unidad de medida",
            icon: "square_foot",
            color: "#a0aec0",
            url: `${BASEURL}/medidas`,
          },
          {
            id: 45,
            title: "Impuestos",
            icon: "account_balance",
            color: "#a0aec0",
            url: `${BASEURL}/impuestos`,
          },
          {
            id: 34,
            title: "Usuarios",
            icon: "manage_accounts",
            color: "#a0aec0",
            url: `${BASEURL}/users`,
          },
        ],
      },
    
      {
        id: 57,
        title: "Ajustes",
        icon: "settings",
        color: "#a0aec0",
        open: false,
        submenu: [
          {
            id: 36,
            title: "Datos de Empresa",
            icon: "admin_panel_settings",
            color: "#a0aec0",
            url: `${BASEURL}/settings`,
          },
          {
            id: 38,
            title: "Registro de facturas",
            icon: "app_registration",
            color: "#a0aec0",
            url: `${BASEURL}/registrofacturas`,
          },
          {
            id: 72,
            title: "Tema y colores",
            icon: "palette",
            color: "#a0aec0",
            url: `${BASEURL}/tema`,
          },
          {
            id: 59,
            title: "Info y ayuda",
            icon: "help",
            color: "#a0aec0",
            url: `${BASEURL}/info`,
          },
        ],
      },  
]