export const Columns = [
    {
        field:'codigo_producto',
        title:'COD.'
    },
    {
        field:'cantidad_producto',
        title:'CANT'
    },
    {
        field:'nombre_producto',
        title:'Producto'
    },
    {
        field:'precio_producto_factura',
        title:'Precio',
        isNumber:true
    },
]